# Generated by Django 4.1.3 on 2022-12-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                ("accept", models.BooleanField(default=False, verbose_name="Принят")),
            ],
            options={
                "verbose_name": "Лид",
                "verbose_name_plural": "Лиды",
                "ordering": ["-data"],
            },
        ),
    ]
