# Generated by Django 4.1.3 on 2022-12-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Leads", new_name="Lead",),
    ]
