# Generated by Django 4.1.3 on 2022-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="adress",
            field=models.CharField(
                choices=[
                    ("Усенбаева 44", "Усенбаева 44"),
                    ("Ибраимова 96", "Ибраимова 96"),
                ],
                max_length=255,
                verbose_name="Адрес",
            ),
        ),
    ]
