# Generated by Django 4.1.3 on 2022-12-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            (1, "Python"),
                            (2, "JavaScript"),
                            (3, "UX/UI"),
                            (4, "Flutter"),
                            (5, "SMM"),
                            (6, "Kids"),
                        ],
                        max_length=225,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "tariff",
                    models.CharField(
                        choices=[(1, "Online"), (2, "Offline"), (3, "Standart+")],
                        max_length=255,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "payment",
                    models.PositiveIntegerField(default=0, verbose_name="Оплата"),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                ("finished", models.DateTimeField(verbose_name="Выпуск")),
                (
                    "certificate",
                    models.FileField(
                        upload_to="certificate/%Y/%m/%d/", verbose_name="Сертификат"
                    ),
                ),
                ("accept", models.BooleanField(default=False, verbose_name="Принят")),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["-data"],
            },
        ),
    ]
