# Generated by Django 4.1.3 on 2022-12-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_student_course_alter_student_tariff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="certificate",
            field=models.FileField(
                blank=True, upload_to="certificate/%Y/%m/%d/", verbose_name="Сертификат"
            ),
        ),
    ]
