# Generated by Django 4.1.3 on 2022-12-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_student_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Python", "Python"),
                    ("JavaScript", "JavaScript"),
                    ("UX/UI", "UX/UI"),
                    ("Flutter", "Flutter"),
                    ("SMM", "SMM"),
                    ("Kids", "Kids"),
                ],
                max_length=225,
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="data",
            field=models.DateTimeField(blank=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="student",
            name="finished",
            field=models.DateTimeField(blank=True, verbose_name="Выпуск"),
        ),
        migrations.AlterField(
            model_name="student",
            name="payment",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Оплата"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="tariff",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Online", "Online"),
                    ("Offline", "Offline"),
                    ("Standart+", "Standart+"),
                ],
                max_length=255,
                verbose_name="Тариф",
            ),
        ),
    ]
