# Generated by Django 4.1.3 on 2022-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyExpenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Наименование"),
                ),
                ("summ", models.PositiveIntegerField(default=0, verbose_name="Сумма")),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Ежемесячный расход",
                "verbose_name_plural": "Ежемесячные расходы",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Наименование"),
                ),
                ("summ", models.PositiveIntegerField(default=0, verbose_name="Сумма")),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Ежемесячное поступление",
                "verbose_name_plural": "Ежемесячные поступления",
                "ordering": ["-data"],
            },
        ),
    ]
